spring:
  main:
    banner-mode: off

  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/key_oa?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  # 数据库初始化数据
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    open-in-view: true

  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

  config:
    import: application-dev.yml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      cors:
        allowed-origin-patterns: "*"

key-oa:
  jwt:
    salt: 1Jvq2wYsh3B2Ex9UZlNwNUMpbCILbvQt
