spring:
  main:
    banner-mode: off

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/key_oa?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai

  # 数据库初始化数据
  sql:
    init:
      data-locations: classpath:sql/data.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    open-in-view: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 8

  config:
    import: application-dev.yml

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      cors:
        allowed-origin-patterns: "*"

key-oa:
  jwt:
    salt: 1Jvq2wYsh3B2Ex9UZlNwNUMpbCILbvQt
